[package]
name = "elixir_tree_sitter"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "elixir_tree_sitter"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
